const fs = require("fs");
const path = require("path");
const { CONTEXT_ROOT, VERSION, buildContext, validateContext, approveContext, initializeFoundationManifest, finalizeFoundationManifest, transitionToImplementation } = require("./core");
const { prepareContext } = require("./prepare");
const { loadRootEnv } = require("./env");
const { initializeEvidence, captureEvidence, linkEvidence, migrateLegacyEvidence } = require("./evidence");
const { buildChangeManifest } = require("./review");
const { buildQcPlan, runQcPlan, allocatePort } = require("./qc");
const { initializeAmendment, buildAmendment, validateAmendment, approveAmendment } = require("./amendment");
const { importDesign, collectFromFigma } = require("../../design-collector/src/core");
const { normalizeFile } = require("../../normalizers/design-normalizer/src/core");

const GROUP_ALIASES = { ctx: "context", amd: "amend", fdn: "foundation", ev: "evidence" };
const LEGACY_ALIASES = { init: "context init", prepare: "context prepare", build: "context build", validate: "context validate", approve: "context approve", status: "context status", import: "design import", collect: "design collect", normalize: "design normalize", "amend-init": "amend create", "amend-build": "amend build", "amend-validate": "amend validate", "amend-approve": "amend approve", "amend-status": "amend status", "init-foundation-manifest": "foundation init", "finalize-foundation-manifest": "foundation finalize", transition: "foundation transition", "init-evidence": "evidence init", "capture-evidence": "evidence capture", "link-evidence": "evidence link", "migrate-evidence": "evidence migrate", "review-input": "review input", "qc-plan": "qc plan", "run-qc": "qc run", "allocate-port": "util allocate-port" };
const BOOLEAN_OPTIONS = new Set(["help", "refresh", "allow-figma-rest", "preparation", "remove-source", "allow-source-drift"]);
const TASK_SEGMENT = /^[a-z0-9][a-z0-9._-]*$/i;
function assert(ok, message) { if (!ok) throw new Error(message); }
function required(options, name) { assert(options[name] !== undefined, `--${name} is required`); return options[name]; }
function resolvePath(value, label) { assert(typeof value === "string" && value.trim(), `${label} is required`); return path.resolve(value); }
function list(value) { return value ? String(value).split(",").map((item) => item.trim()).filter(Boolean) : []; }
function number(value, fallback) { return value === undefined ? fallback : Number(value); }
function parseOptions(tokens) { const result = {}; for (let i = 0; i < tokens.length; i += 1) { const token = tokens[i]; assert(token.startsWith("--"), `Unexpected argument: ${token}`); const [name, inline] = token.slice(2).split(/=(.*)/s); assert(!result[name], `Option may be supplied once only: --${name}`); if (BOOLEAN_OPTIONS.has(name)) { assert(inline === undefined, `Boolean option cannot have a value: --${name}`); result[name] = true; } else { const value = inline === undefined ? tokens[++i] : inline; assert(value !== undefined && !value.startsWith("--"), `Option requires a value: --${name}`); result[name] = value; } } return result; }
function resolveCommand(argv) { const [first, second, ...rest] = argv; if (!first || first === "--help" || first === "-h") return { help: true }; if (LEGACY_ALIASES[first]) { const [group, action] = LEGACY_ALIASES[first].split(" "); return { group, action, tokens: [second, ...rest].filter(Boolean), legacy: first }; } const group = GROUP_ALIASES[first] || first; if (!second || second === "--help" || second === "-h") return { help: true, group }; return { group, action: second, tokens: rest }; }
function helpText(group) { const groups = { context: "init, prepare, build, validate, approve, status", design: "import, collect, normalize", amend: "create, build, validate, approve, status", foundation: "init, finalize, transition", evidence: "init, capture, link, migrate", review: "input", qc: "plan, run", util: "allocate-port" }; assert(!group || groups[group], `Unknown command group: ${group}`); return group ? `Usage: figma-context ${group} <${groups[group]}> [options]` : `Usage: figma-context <group> <command> [options]\n\n${Object.entries(groups).map(([name, commands]) => `  ${name}: ${commands}`).join("\n")}\n\nRun: figma-context <group> --help`; }
function resolveTaskContext(task) { const parts = String(task || "").replace(/\\/g, "/").split("/"); assert(parts.length === 2 && parts.every((part) => TASK_SEGMENT.test(part)), "--task must use <project-key>/<task-id> with safe path segments"); const root = path.resolve(CONTEXT_ROOT, "tasks"); const candidate = path.resolve(root, parts[0], parts[1], "task-context.approved.json"); const relative = path.relative(root, candidate); assert(relative && !relative.startsWith("..") && !path.isAbsolute(relative), "--task escapes contexts/tasks"); assert(fs.existsSync(candidate), `Approved task context does not exist: ${candidate}`); return candidate; }
function contextOption(options, allowTask = true) { assert(!(options.context && options.task), "Use either --context or --task, not both"); if (options.task) { assert(allowTask, "--task is only available for approved context commands"); return resolveTaskContext(options.task); } return resolvePath(required(options, "context"), "--context"); }
function meta(result, command, legacy) { return { ...(result || {}), meta: { command, cliVersion: VERSION, legacyAlias: Boolean(legacy), warnings: legacy ? [`Legacy command '${legacy}' is supported for compatibility. Use '${command}'.`] : [] } }; }
function copyTemplate(out) { const target = resolvePath(out, "--out"); assert(!fs.existsSync(target), `Refusing to overwrite existing intake: ${target}`); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.copyFileSync(path.join(__dirname, "..", "templates", "intake.template.json"), target); return { intakePath: target }; }
async function execute(argv) { const parsed = resolveCommand(argv); if (parsed.help) return { help: helpText(parsed.group) }; const o = parseOptions(parsed.tokens); if (o.help) return { help: helpText(parsed.group) }; const cmd = `${parsed.group} ${parsed.action}`; const phase = o.phase; const tokenEnv = o["token-env"] || "FIGMA_ACCESS_TOKEN"; let result;
  if (cmd === "context init") result = copyTemplate(required(o, "out")); else if (cmd === "context build") result = buildContext(JSON.parse(fs.readFileSync(resolvePath(required(o, "intake"), "--intake"), "utf8"))); else if (cmd === "context prepare") result = await prepareContext({ intakePath: resolvePath(required(o, "intake"), "--intake"), designJsonPath: o["design-json"], figmaUrl: o["figma-url"], outPath: o.out, resolvedIntakePath: o["write-resolved-intake"], nodeIds: list(o["node-ids"]), phase, depth: number(o.depth, 10), maxDepth: number(o["max-depth"], 10), maxChildren: number(o["max-children"], 100), refresh: Boolean(o.refresh), allowFigmaRest: Boolean(o["allow-figma-rest"]), tokenEnv, version: o.version }); else if (cmd === "context validate") result = validateContext(contextOption(o, false), { phase }); else if (cmd === "context approve") result = approveContext(contextOption(o, false)); else if (cmd === "context status") result = validateContext(contextOption(o), { requireApproved: true, phase, allowSourceDrift: Boolean(o["allow-source-drift"]) });
  else if (cmd === "design import") result = importDesign({ inputPath: resolvePath(required(o, "input"), "--input"), outPath: resolvePath(required(o, "out"), "--out"), figmaUrl: o["figma-url"], nodeIds: list(o["node-ids"]), maxDepth: number(o["max-depth"], 10), maxChildren: number(o["max-children"], 100) }); else if (cmd === "design collect") { assert(o["allow-figma-rest"], "design collect requires explicit --allow-figma-rest"); loadRootEnv([tokenEnv]); result = await collectFromFigma({ figmaUrl: required(o, "figma-url"), outPath: resolvePath(required(o, "out"), "--out"), nodeIds: list(o["node-ids"]), depth: number(o.depth, 10), maxDepth: number(o["max-depth"], 10), maxChildren: number(o["max-children"], 100), refresh: Boolean(o.refresh), tokenEnv, version: o.version }); } else if (cmd === "design normalize") result = normalizeFile(resolvePath(required(o, "input"), "--input"), resolvePath(required(o, "out"), "--out"), { targetNodeId: o["target-node-id"] });
  else if (cmd === "amend create") result = initializeAmendment(resolvePath(required(o, "base"), "--base"), required(o, "id")); else if (cmd === "amend build") result = buildAmendment(JSON.parse(fs.readFileSync(resolvePath(required(o, "input"), "--input"), "utf8"))); else if (cmd === "amend validate") result = validateAmendment(resolvePath(required(o, "amendment"), "--amendment"), { phase }); else if (cmd === "amend approve") result = approveAmendment(resolvePath(required(o, "amendment"), "--amendment")); else if (cmd === "amend status") result = validateAmendment(resolvePath(required(o, "amendment"), "--amendment"), { requireApproved: true, phase });
  else if (cmd === "foundation init") result = initializeFoundationManifest(contextOption(o)); else if (cmd === "foundation finalize") result = finalizeFoundationManifest(contextOption(o), { foundationManifestPath: o["foundation-manifest"] }); else if (cmd === "foundation transition") result = transitionToImplementation(resolvePath(required(o, "from"), "--from"), JSON.parse(fs.readFileSync(resolvePath(required(o, "intake"), "--intake"), "utf8")), { foundationManifestPath: o["foundation-manifest"] });
  else if (cmd === "evidence init") result = initializeEvidence(contextOption(o), { phase: phase || "implementation", preparation: Boolean(o.preparation) }); else if (cmd === "evidence capture") result = await captureEvidence({ contextPath: contextOption(o), phase: phase || "implementation", url: required(o, "url"), screen: required(o, "screen"), state: o.state, viewport: required(o, "viewport"), dpr: o.dpr, zoom: o.zoom, readySelector: o["ready-selector"], waitMs: o["wait-ms"], nodeId: o["node-id"], referenceImage: o["reference-image"], fonts: o.fonts, assets: o.assets, dataSeed: o["data-seed"], testCases: list(o["test-cases"]), amendmentPath: o.amendment && resolvePath(o.amendment, "--amendment") }); else if (cmd === "evidence link") result = linkEvidence(contextOption(o), { phase: phase || "review", amendmentPath: o.amendment && resolvePath(o.amendment, "--amendment") }); else if (cmd === "evidence migrate") result = migrateLegacyEvidence(contextOption(o), resolvePath(required(o, "from"), "--from"), Boolean(o["remove-source"]), { preparation: Boolean(o.preparation), phase: phase || "implementation" });
  else if (cmd === "review input") result = buildChangeManifest(contextOption(o), { changedFiles: list(o["changed-files"]), amendmentPath: o.amendment && resolvePath(o.amendment, "--amendment") }); else if (cmd === "qc plan") result = buildQcPlan(contextOption(o), { url: required(o, "url"), screen: o.screen, readySelector: o["ready-selector"], dpr: o.dpr, zoom: o.zoom, fonts: o.fonts, assets: o.assets, dataSeed: o["data-seed"], testCases: list(o["test-cases"]), amendmentPath: o.amendment && resolvePath(o.amendment, "--amendment") }); else if (cmd === "qc run") result = await runQcPlan(contextOption(o), { planPath: o.plan && resolvePath(o.plan, "--plan"), amendmentPath: o.amendment && resolvePath(o.amendment, "--amendment") }); else if (cmd === "util allocate-port") result = await allocatePort(o.host || "127.0.0.1"); else throw new Error(`Unknown command: ${cmd}. Run 'figma-context --help'.`);
  return meta(result, cmd, parsed.legacy); }
module.exports = { execute, parseOptions, resolveCommand, resolveTaskContext, helpText, LEGACY_ALIASES };
